# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FTP.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(705, 719)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.connectBox = QtWidgets.QGroupBox(self.centralwidget)
        self.connectBox.setGeometry(QtCore.QRect(20, 10, 661, 211))
        self.connectBox.setObjectName("connectBox")
        self.usernameLabel = QtWidgets.QLabel(self.connectBox)
        self.usernameLabel.setGeometry(QtCore.QRect(20, 30, 71, 17))
        self.usernameLabel.setObjectName("usernameLabel")
        self.connectButton = QtWidgets.QPushButton(self.connectBox)
        self.connectButton.setGeometry(QtCore.QRect(260, 30, 191, 51))
        self.connectButton.setObjectName("connectButton")
        self.passwordLabel = QtWidgets.QLabel(self.connectBox)
        self.passwordLabel.setGeometry(QtCore.QRect(20, 70, 61, 17))
        self.passwordLabel.setObjectName("passwordLabel")
        self.outputList = QtWidgets.QListWidget(self.connectBox)
        self.outputList.setGeometry(QtCore.QRect(260, 100, 391, 101))
        self.outputList.setObjectName("outputList")
        self.usernameLine = QtWidgets.QLineEdit(self.connectBox)
        self.usernameLine.setGeometry(QtCore.QRect(110, 30, 131, 31))
        self.usernameLine.setAutoFillBackground(True)
        self.usernameLine.setObjectName("usernameLine")
        self.hostnameLine = QtWidgets.QLineEdit(self.connectBox)
        self.hostnameLine.setGeometry(QtCore.QRect(110, 110, 131, 29))
        self.hostnameLine.setAutoFillBackground(True)
        self.hostnameLine.setObjectName("hostnameLine")
        self.disconnectButton = QtWidgets.QPushButton(self.connectBox)
        self.disconnectButton.setGeometry(QtCore.QRect(460, 30, 191, 51))
        self.disconnectButton.setObjectName("disconnectButton")
        self.passswordLine = QtWidgets.QLineEdit(self.connectBox)
        self.passswordLine.setGeometry(QtCore.QRect(110, 70, 131, 29))
        self.passswordLine.setAutoFillBackground(True)
        self.passswordLine.setObjectName("passswordLine")
        self.hostnameLabel = QtWidgets.QLabel(self.connectBox)
        self.hostnameLabel.setGeometry(QtCore.QRect(20, 110, 81, 17))
        self.hostnameLabel.setObjectName("hostnameLabel")
        self.transferBox = QtWidgets.QGroupBox(self.centralwidget)
        self.transferBox.setGeometry(QtCore.QRect(20, 230, 661, 441))
        self.transferBox.setObjectName("transferBox")
        self.serverDirLabel = QtWidgets.QLabel(self.transferBox)
        self.serverDirLabel.setGeometry(QtCore.QRect(400, 30, 101, 17))
        self.serverDirLabel.setObjectName("serverDirLabel")
        self.refreshButton = QtWidgets.QPushButton(self.transferBox)
        self.refreshButton.setGeometry(QtCore.QRect(290, 80, 87, 29))
        self.refreshButton.setObjectName("refreshButton")
        self.storeButton = QtWidgets.QPushButton(self.transferBox)
        self.storeButton.setGeometry(QtCore.QRect(290, 120, 87, 29))
        self.storeButton.setObjectName("storeButton")
        self.retrieveButton = QtWidgets.QPushButton(self.transferBox)
        self.retrieveButton.setGeometry(QtCore.QRect(290, 160, 87, 29))
        self.retrieveButton.setObjectName("retrieveButton")
        self.serverDirList = QtWidgets.QListWidget(self.transferBox)
        self.serverDirList.setGeometry(QtCore.QRect(400, 60, 251, 371))
        self.serverDirList.setObjectName("serverDirList")
        self.localDirLabel = QtWidgets.QLabel(self.transferBox)
        self.localDirLabel.setGeometry(QtCore.QRect(20, 30, 91, 17))
        self.localDirLabel.setObjectName("localDirLabel")
        self.localDirList = QtWidgets.QListWidget(self.transferBox)
        self.localDirList.setGeometry(QtCore.QRect(20, 60, 251, 371))
        self.localDirList.setObjectName("localDirList")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(mainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionPreferences = QtWidgets.QAction(mainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAbout = QtWidgets.QAction(mainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "SecureFile"))
        self.connectBox.setTitle(_translate("mainWindow", "Connect"))
        self.usernameLabel.setText(_translate("mainWindow", "Username:"))
        self.connectButton.setText(_translate("mainWindow", "Connect"))
        self.passwordLabel.setText(_translate("mainWindow", "Password:"))
        self.disconnectButton.setText(_translate("mainWindow", "Disconnect"))
        self.hostnameLabel.setText(_translate("mainWindow", "Hostname/IP:"))
        self.transferBox.setTitle(_translate("mainWindow", "Transfer"))
        self.serverDirLabel.setText(_translate("mainWindow", "Server Directory:"))
        self.refreshButton.setText(_translate("mainWindow", "Refresh"))
        self.storeButton.setText(_translate("mainWindow", "Store --->"))
        self.retrieveButton.setText(_translate("mainWindow", "<--- Retrieve"))
        self.localDirLabel.setText(_translate("mainWindow", "Local Directory:"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.menuEdit.setTitle(_translate("mainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("mainWindow", "Help"))
        self.actionExit.setText(_translate("mainWindow", "Exit"))
        self.actionPreferences.setText(_translate("mainWindow", "Preferences"))
        self.actionAbout.setText(_translate("mainWindow", "About"))
