# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 793)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.connectionBox = QtWidgets.QGroupBox(self.centralwidget)
        self.connectionBox.setGeometry(QtCore.QRect(20, 10, 741, 161))
        self.connectionBox.setObjectName("connectionBox")
        self.serverLabel = QtWidgets.QLabel(self.connectionBox)
        self.serverLabel.setGeometry(QtCore.QRect(30, 40, 111, 17))
        self.serverLabel.setObjectName("serverLabel")
        self.portLabel = QtWidgets.QLabel(self.connectionBox)
        self.portLabel.setGeometry(QtCore.QRect(320, 40, 31, 17))
        self.portLabel.setObjectName("portLabel")
        self.usernameLabel = QtWidgets.QLabel(self.connectionBox)
        self.usernameLabel.setGeometry(QtCore.QRect(530, 40, 71, 17))
        self.usernameLabel.setObjectName("usernameLabel")
        self.hostnameLabel = QtWidgets.QLabel(self.connectionBox)
        self.hostnameLabel.setGeometry(QtCore.QRect(30, 100, 71, 17))
        self.hostnameLabel.setObjectName("hostnameLabel")
        self.speedLabel = QtWidgets.QLabel(self.connectionBox)
        self.speedLabel.setGeometry(QtCore.QRect(230, 100, 41, 17))
        self.speedLabel.setObjectName("speedLabel")
        self.speedDropdown = QtWidgets.QComboBox(self.connectionBox)
        self.speedDropdown.setGeometry(QtCore.QRect(280, 100, 121, 31))
        self.speedDropdown.setObjectName("speedDropdown")
        self.speedDropdown.addItem("")
        self.speedDropdown.addItem("")
        self.connectButton = QtWidgets.QPushButton(self.connectionBox)
        self.connectButton.setGeometry(QtCore.QRect(420, 100, 311, 51))
        self.connectButton.setObjectName("connectButton")
        self.serverLine = QtWidgets.QLineEdit(self.connectionBox)
        self.serverLine.setGeometry(QtCore.QRect(140, 40, 161, 29))
        self.serverLine.setAutoFillBackground(True)
        self.serverLine.setObjectName("serverLine")
        self.portLine = QtWidgets.QLineEdit(self.connectionBox)
        self.portLine.setGeometry(QtCore.QRect(350, 40, 161, 29))
        self.portLine.setAutoFillBackground(True)
        self.portLine.setObjectName("portLine")
        self.usernameLine = QtWidgets.QLineEdit(self.connectionBox)
        self.usernameLine.setGeometry(QtCore.QRect(600, 40, 131, 29))
        self.usernameLine.setAutoFillBackground(True)
        self.usernameLine.setObjectName("usernameLine")
        self.hostnameLine = QtWidgets.QLineEdit(self.connectionBox)
        self.hostnameLine.setGeometry(QtCore.QRect(100, 100, 113, 29))
        self.hostnameLine.setAutoFillBackground(True)
        self.hostnameLine.setObjectName("hostnameLine")
        self.searchBox = QtWidgets.QGroupBox(self.centralwidget)
        self.searchBox.setGeometry(QtCore.QRect(20, 190, 741, 261))
        self.searchBox.setObjectName("searchBox")
        self.keywordLabel = QtWidgets.QLabel(self.searchBox)
        self.keywordLabel.setGeometry(QtCore.QRect(30, 40, 61, 17))
        self.keywordLabel.setObjectName("keywordLabel")
        self.searchButton = QtWidgets.QPushButton(self.searchBox)
        self.searchButton.setGeometry(QtCore.QRect(420, 30, 111, 41))
        self.searchButton.setObjectName("searchButton")
        self.keywordLine = QtWidgets.QLineEdit(self.searchBox)
        self.keywordLine.setGeometry(QtCore.QRect(130, 40, 271, 29))
        self.keywordLine.setAutoFillBackground(True)
        self.keywordLine.setObjectName("keywordLine")
        self.searchTable = QtWidgets.QTableWidget(self.searchBox)
        self.searchTable.setGeometry(QtCore.QRect(90, 90, 641, 161))
        self.searchTable.setObjectName("searchTable")
        self.searchTable.setColumnCount(4)
        self.searchTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.searchTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchTable.setHorizontalHeaderItem(3, item)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 480, 741, 261))
        self.groupBox.setObjectName("groupBox")
        self.commandLabel = QtWidgets.QLabel(self.groupBox)
        self.commandLabel.setGeometry(QtCore.QRect(30, 40, 101, 17))
        self.commandLabel.setObjectName("commandLabel")
        self.goButton = QtWidgets.QPushButton(self.groupBox)
        self.goButton.setGeometry(QtCore.QRect(420, 30, 111, 41))
        self.goButton.setObjectName("goButton")
        self.commandLine = QtWidgets.QLineEdit(self.groupBox)
        self.commandLine.setGeometry(QtCore.QRect(130, 40, 271, 29))
        self.commandLine.setAutoFillBackground(True)
        self.commandLine.setObjectName("commandLine")
        self.commandList = QtWidgets.QListWidget(self.groupBox)
        self.commandList.setGeometry(QtCore.QRect(90, 90, 641, 161))
        self.commandList.setObjectName("commandList")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Host"))
        self.connectionBox.setTitle(_translate("MainWindow", "Connection"))
        self.serverLabel.setText(_translate("MainWindow", "Server Hostname:"))
        self.portLabel.setText(_translate("MainWindow", "Port:"))
        self.usernameLabel.setText(_translate("MainWindow", "Username:"))
        self.hostnameLabel.setText(_translate("MainWindow", "Hostname:"))
        self.speedLabel.setText(_translate("MainWindow", "Speed:"))
        self.speedDropdown.setItemText(0, _translate("MainWindow", "Ethernet"))
        self.speedDropdown.setItemText(1, _translate("MainWindow", "T1"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.searchBox.setTitle(_translate("MainWindow", "Search"))
        self.keywordLabel.setText(_translate("MainWindow", "Keyword:"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        item = self.searchTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Files"))
        item = self.searchTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Info"))
        item = self.searchTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Location"))
        item = self.searchTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Speed"))
        self.groupBox.setTitle(_translate("MainWindow", "FTP"))
        self.commandLabel.setText(_translate("MainWindow", "Command:"))
        self.goButton.setText(_translate("MainWindow", "Make it so"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
